### ISSUE TITLE
Error message when attempting to input password

### ISSUE THREAD

**Issue by LustStarrr** [unofficial-protonmail-desktop/application#619]
Upon attempting to input password, the following error message occurs:

> Are you connected?
> Login page couldnt be loaded due to the following error:
> 
> CRASHED
> 
> Please check your internet connection and try to reload the page.

My internet connection is working fine, & the issue appears to be linked to the first keystroke being typed into the password field, rather than when the page is attempting to load, so it doesn't appear to be connection-related, in my opinion. Problem only began occurring after the most recent update.

**Comment by kontrollanten** [comment]
Thanks for reporting. Sounds like a strange problem, maybe it's related to electron. Which OS are you using? Can you try to clone the repo and run the latest version with `yarn start`?
