### ISSUE TITLE
No desktop notification(Arch Linux)

### ISSUE THREAD

**Issue by Ferryistaken** [unofficial-protonmail-desktop/application#643]
I installed the latest version from the AUR, everything works perfectly but I don't receive any notifications. I use notify-osd as my notification server

**Comment by kontrollanten** [comment]
That sounds strange. If you open the application from the terminal and trigger a notification (by sending yourself an email), is there any error in the terminal?

**Comment by Ferryistaken** [comment]
I rebooted and it started working sorry for the hassle
